#ifndef COMMON_H
#define COMMON_H

/*
 * include autogenerated config header
 */

#include "config.h"

/*
 * common headers
 */

#include "defs.h"
#include "inc.h"
#include "posix/defs.h"
#include "types/defs.h"
#include "io/defs.h"

#endif
